service: dynamo-stream-lab

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
            

functions:
  readStream:
    handler: handler.handler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:200881451636:table/sell_gsi/stream/2021-09-15T20:45:24.652
          batchSize: 1
          maximumRetryAttempts: 10
          enabled: true